/* 
 * Sample Password Flow OAuth2 Project
 *
 * This is an example of using OAuth2 Password Flow in a specification to describe security to your API. Rate Limiting is applied to ensure fair usage and prevent abuse.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DefaultApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DefaultApiTests
    {
        private DefaultApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DefaultApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DefaultApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DefaultApi
            //Assert.IsInstanceOfType(typeof(DefaultApi), instance, "instance is a DefaultApi");
        }

        /// <summary>
        /// Test CreateLuggage
        /// </summary>
        [Test]
        public void CreateLuggageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //LuggageCreate body = null;
            //var response = instance.CreateLuggage(body);
            //Assert.IsInstanceOf<Luggage> (response, "response is Luggage");
        }
        /// <summary>
        /// Test DeleteLuggage
        /// </summary>
        [Test]
        public void DeleteLuggageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string luggageId = null;
            //instance.DeleteLuggage(luggageId);
            
        }
        /// <summary>
        /// Test ExampleGet
        /// </summary>
        [Test]
        public void ExampleGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ExampleGet();
            
        }
        /// <summary>
        /// Test GetLuggageById
        /// </summary>
        [Test]
        public void GetLuggageByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string luggageId = null;
            //var response = instance.GetLuggageById(luggageId);
            //Assert.IsInstanceOf<Luggage> (response, "response is Luggage");
        }
        /// <summary>
        /// Test ListLuggage
        /// </summary>
        [Test]
        public void ListLuggageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListLuggage();
            //Assert.IsInstanceOf<List<Luggage>> (response, "response is List<Luggage>");
        }
        /// <summary>
        /// Test PingGet
        /// </summary>
        [Test]
        public void PingGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.PingGet();
            
        }
        /// <summary>
        /// Test UpdateLuggage
        /// </summary>
        [Test]
        public void UpdateLuggageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //LuggageUpdate body = null;
            //string luggageId = null;
            //var response = instance.UpdateLuggage(body, luggageId);
            //Assert.IsInstanceOf<Luggage> (response, "response is Luggage");
        }
    }

}
