/* 
 * Sample Password Flow OAuth2 Project
 *
 * This is an example of using OAuth2 Password Flow in a specification to describe security to your API. Rate Limiting is applied to ensure fair usage and prevent abuse.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// A luggage item in the airport system
    /// </summary>
    [DataContract]
        public partial class Luggage :  IEquatable<Luggage>, IValidatableObject
    {
        /// <summary>
        /// Current status of the luggage
        /// </summary>
        /// <value>Current status of the luggage</value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum StatusEnum
        {
            /// <summary>
            /// Enum CheckedIn for value: checked-in
            /// </summary>
            [EnumMember(Value = "checked-in")]
            CheckedIn = 1,
            /// <summary>
            /// Enum InTransit for value: in-transit
            /// </summary>
            [EnumMember(Value = "in-transit")]
            InTransit = 2,
            /// <summary>
            /// Enum Delivered for value: delivered
            /// </summary>
            [EnumMember(Value = "delivered")]
            Delivered = 3,
            /// <summary>
            /// Enum Lost for value: lost
            /// </summary>
            [EnumMember(Value = "lost")]
            Lost = 4        }
        /// <summary>
        /// Current status of the luggage
        /// </summary>
        /// <value>Current status of the luggage</value>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public StatusEnum? Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Luggage" /> class.
        /// </summary>
        /// <param name="id">Unique identifier for the luggage.</param>
        /// <param name="ownerName">Name of the luggage owner.</param>
        /// <param name="flightNumber">Flight number associated with the luggage.</param>
        /// <param name="weight">Weight of the luggage in kilograms.</param>
        /// <param name="status">Current status of the luggage.</param>
        public Luggage(string id = default(string), string ownerName = default(string), string flightNumber = default(string), float? weight = default(float?), StatusEnum? status = default(StatusEnum?))
        {
            this.Id = id;
            this.OwnerName = ownerName;
            this.FlightNumber = flightNumber;
            this.Weight = weight;
            this.Status = status;
        }
        
        /// <summary>
        /// Unique identifier for the luggage
        /// </summary>
        /// <value>Unique identifier for the luggage</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// Name of the luggage owner
        /// </summary>
        /// <value>Name of the luggage owner</value>
        [DataMember(Name="ownerName", EmitDefaultValue=false)]
        public string OwnerName { get; set; }

        /// <summary>
        /// Flight number associated with the luggage
        /// </summary>
        /// <value>Flight number associated with the luggage</value>
        [DataMember(Name="flightNumber", EmitDefaultValue=false)]
        public string FlightNumber { get; set; }

        /// <summary>
        /// Weight of the luggage in kilograms
        /// </summary>
        /// <value>Weight of the luggage in kilograms</value>
        [DataMember(Name="weight", EmitDefaultValue=false)]
        public float? Weight { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Luggage {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  OwnerName: ").Append(OwnerName).Append("\n");
            sb.Append("  FlightNumber: ").Append(FlightNumber).Append("\n");
            sb.Append("  Weight: ").Append(Weight).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Luggage);
        }

        /// <summary>
        /// Returns true if Luggage instances are equal
        /// </summary>
        /// <param name="input">Instance of Luggage to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Luggage input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.OwnerName == input.OwnerName ||
                    (this.OwnerName != null &&
                    this.OwnerName.Equals(input.OwnerName))
                ) && 
                (
                    this.FlightNumber == input.FlightNumber ||
                    (this.FlightNumber != null &&
                    this.FlightNumber.Equals(input.FlightNumber))
                ) && 
                (
                    this.Weight == input.Weight ||
                    (this.Weight != null &&
                    this.Weight.Equals(input.Weight))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.OwnerName != null)
                    hashCode = hashCode * 59 + this.OwnerName.GetHashCode();
                if (this.FlightNumber != null)
                    hashCode = hashCode * 59 + this.FlightNumber.GetHashCode();
                if (this.Weight != null)
                    hashCode = hashCode * 59 + this.Weight.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
