/* 
 * Sample Password Flow OAuth2 Project
 *
 * This is an example of using OAuth2 Password Flow in a specification to describe security to your API. Rate Limiting is applied to ensure fair usage and prevent abuse.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Payload to create a new luggage item
    /// </summary>
    [DataContract]
        public partial class LuggageCreate :  IEquatable<LuggageCreate>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LuggageCreate" /> class.
        /// </summary>
        /// <param name="ownerName">Name of the luggage owner (required).</param>
        /// <param name="flightNumber">Flight number associated with the luggage (required).</param>
        /// <param name="weight">Weight of the luggage in kilograms (required).</param>
        public LuggageCreate(string ownerName = default(string), string flightNumber = default(string), float? weight = default(float?))
        {
            // to ensure "ownerName" is required (not null)
            if (ownerName == null)
            {
                throw new InvalidDataException("ownerName is a required property for LuggageCreate and cannot be null");
            }
            else
            {
                this.OwnerName = ownerName;
            }
            // to ensure "flightNumber" is required (not null)
            if (flightNumber == null)
            {
                throw new InvalidDataException("flightNumber is a required property for LuggageCreate and cannot be null");
            }
            else
            {
                this.FlightNumber = flightNumber;
            }
            // to ensure "weight" is required (not null)
            if (weight == null)
            {
                throw new InvalidDataException("weight is a required property for LuggageCreate and cannot be null");
            }
            else
            {
                this.Weight = weight;
            }
        }
        
        /// <summary>
        /// Name of the luggage owner
        /// </summary>
        /// <value>Name of the luggage owner</value>
        [DataMember(Name="ownerName", EmitDefaultValue=false)]
        public string OwnerName { get; set; }

        /// <summary>
        /// Flight number associated with the luggage
        /// </summary>
        /// <value>Flight number associated with the luggage</value>
        [DataMember(Name="flightNumber", EmitDefaultValue=false)]
        public string FlightNumber { get; set; }

        /// <summary>
        /// Weight of the luggage in kilograms
        /// </summary>
        /// <value>Weight of the luggage in kilograms</value>
        [DataMember(Name="weight", EmitDefaultValue=false)]
        public float? Weight { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LuggageCreate {\n");
            sb.Append("  OwnerName: ").Append(OwnerName).Append("\n");
            sb.Append("  FlightNumber: ").Append(FlightNumber).Append("\n");
            sb.Append("  Weight: ").Append(Weight).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LuggageCreate);
        }

        /// <summary>
        /// Returns true if LuggageCreate instances are equal
        /// </summary>
        /// <param name="input">Instance of LuggageCreate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LuggageCreate input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.OwnerName == input.OwnerName ||
                    (this.OwnerName != null &&
                    this.OwnerName.Equals(input.OwnerName))
                ) && 
                (
                    this.FlightNumber == input.FlightNumber ||
                    (this.FlightNumber != null &&
                    this.FlightNumber.Equals(input.FlightNumber))
                ) && 
                (
                    this.Weight == input.Weight ||
                    (this.Weight != null &&
                    this.Weight.Equals(input.Weight))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OwnerName != null)
                    hashCode = hashCode * 59 + this.OwnerName.GetHashCode();
                if (this.FlightNumber != null)
                    hashCode = hashCode * 59 + this.FlightNumber.GetHashCode();
                if (this.Weight != null)
                    hashCode = hashCode * 59 + this.Weight.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
