/* 
 * Sample Password Flow OAuth2 Project
 *
 * This is an example of using OAuth2 Password Flow in a specification to describe security to your API. Rate Limiting is applied to ensure fair usage and prevent abuse.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LuggageCreate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LuggageCreateTests
    {
        // TODO uncomment below to declare an instance variable for LuggageCreate
        //private LuggageCreate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LuggageCreate
            //instance = new LuggageCreate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LuggageCreate
        /// </summary>
        [Test]
        public void LuggageCreateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LuggageCreate
            //Assert.IsInstanceOfType<LuggageCreate> (instance, "variable 'instance' is a LuggageCreate");
        }


        /// <summary>
        /// Test the property 'OwnerName'
        /// </summary>
        [Test]
        public void OwnerNameTest()
        {
            // TODO unit test for the property 'OwnerName'
        }
        /// <summary>
        /// Test the property 'FlightNumber'
        /// </summary>
        [Test]
        public void FlightNumberTest()
        {
            // TODO unit test for the property 'FlightNumber'
        }
        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Test]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }

    }

}
