/* 
 * Sample Password Flow OAuth2 Project
 *
 * This is an example of using OAuth2 Password Flow in a specification to describe security to your API. Rate Limiting is applied to ensure fair usage and prevent abuse.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IDefaultApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create a new luggage item
        /// </summary>
        /// <remarks>
        /// Create a new luggage record in the system. Rate Limiting applies to this endpoint.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Luggage</returns>
        Luggage CreateLuggage (LuggageCreate body);

        /// <summary>
        /// Create a new luggage item
        /// </summary>
        /// <remarks>
        /// Create a new luggage record in the system. Rate Limiting applies to this endpoint.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>ApiResponse of Luggage</returns>
        ApiResponse<Luggage> CreateLuggageWithHttpInfo (LuggageCreate body);
        /// <summary>
        /// Delete a luggage item
        /// </summary>
        /// <remarks>
        /// Remove a luggage item from the system. Rate Limiting applies to this endpoint.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="luggageId"></param>
        /// <returns></returns>
        void DeleteLuggage (string luggageId);

        /// <summary>
        /// Delete a luggage item
        /// </summary>
        /// <remarks>
        /// Remove a luggage item from the system. Rate Limiting applies to this endpoint.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="luggageId"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteLuggageWithHttpInfo (string luggageId);
        /// <summary>
        /// Server example operation
        /// </summary>
        /// <remarks>
        /// This is an example operation to show how security is applied to the call. Rate Limiting is enforced to protect the API.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns></returns>
        void ExampleGet ();

        /// <summary>
        /// Server example operation
        /// </summary>
        /// <remarks>
        /// This is an example operation to show how security is applied to the call. Rate Limiting is enforced to protect the API.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ExampleGetWithHttpInfo ();
        /// <summary>
        /// Retrieve a luggage item by ID
        /// </summary>
        /// <remarks>
        /// Get detailed information about a specific luggage item. Rate Limiting applies to this endpoint.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="luggageId"></param>
        /// <returns>Luggage</returns>
        Luggage GetLuggageById (string luggageId);

        /// <summary>
        /// Retrieve a luggage item by ID
        /// </summary>
        /// <remarks>
        /// Get detailed information about a specific luggage item. Rate Limiting applies to this endpoint.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="luggageId"></param>
        /// <returns>ApiResponse of Luggage</returns>
        ApiResponse<Luggage> GetLuggageByIdWithHttpInfo (string luggageId);
        /// <summary>
        /// List all luggage items
        /// </summary>
        /// <remarks>
        /// Retrieve a list of all luggage items in the system. Rate Limiting applies to this endpoint.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;Luggage&gt;</returns>
        List<Luggage> ListLuggage ();

        /// <summary>
        /// List all luggage items
        /// </summary>
        /// <remarks>
        /// Retrieve a list of all luggage items in the system. Rate Limiting applies to this endpoint.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;Luggage&gt;</returns>
        ApiResponse<List<Luggage>> ListLuggageWithHttpInfo ();
        /// <summary>
        /// Server heartbeat operation
        /// </summary>
        /// <remarks>
        /// This operation shows how to override the global security defined above, as we want to open it up for all users. Rate Limiting is not applied here.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns></returns>
        void PingGet ();

        /// <summary>
        /// Server heartbeat operation
        /// </summary>
        /// <remarks>
        /// This operation shows how to override the global security defined above, as we want to open it up for all users. Rate Limiting is not applied here.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> PingGetWithHttpInfo ();
        /// <summary>
        /// Update a luggage item
        /// </summary>
        /// <remarks>
        /// Update details of an existing luggage item. Rate Limiting applies to this endpoint.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="luggageId"></param>
        /// <returns>Luggage</returns>
        Luggage UpdateLuggage (LuggageUpdate body, string luggageId);

        /// <summary>
        /// Update a luggage item
        /// </summary>
        /// <remarks>
        /// Update details of an existing luggage item. Rate Limiting applies to this endpoint.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="luggageId"></param>
        /// <returns>ApiResponse of Luggage</returns>
        ApiResponse<Luggage> UpdateLuggageWithHttpInfo (LuggageUpdate body, string luggageId);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Create a new luggage item
        /// </summary>
        /// <remarks>
        /// Create a new luggage record in the system. Rate Limiting applies to this endpoint.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of Luggage</returns>
        System.Threading.Tasks.Task<Luggage> CreateLuggageAsync (LuggageCreate body);

        /// <summary>
        /// Create a new luggage item
        /// </summary>
        /// <remarks>
        /// Create a new luggage record in the system. Rate Limiting applies to this endpoint.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (Luggage)</returns>
        System.Threading.Tasks.Task<ApiResponse<Luggage>> CreateLuggageAsyncWithHttpInfo (LuggageCreate body);
        /// <summary>
        /// Delete a luggage item
        /// </summary>
        /// <remarks>
        /// Remove a luggage item from the system. Rate Limiting applies to this endpoint.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="luggageId"></param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteLuggageAsync (string luggageId);

        /// <summary>
        /// Delete a luggage item
        /// </summary>
        /// <remarks>
        /// Remove a luggage item from the system. Rate Limiting applies to this endpoint.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="luggageId"></param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteLuggageAsyncWithHttpInfo (string luggageId);
        /// <summary>
        /// Server example operation
        /// </summary>
        /// <remarks>
        /// This is an example operation to show how security is applied to the call. Rate Limiting is enforced to protect the API.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ExampleGetAsync ();

        /// <summary>
        /// Server example operation
        /// </summary>
        /// <remarks>
        /// This is an example operation to show how security is applied to the call. Rate Limiting is enforced to protect the API.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ExampleGetAsyncWithHttpInfo ();
        /// <summary>
        /// Retrieve a luggage item by ID
        /// </summary>
        /// <remarks>
        /// Get detailed information about a specific luggage item. Rate Limiting applies to this endpoint.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="luggageId"></param>
        /// <returns>Task of Luggage</returns>
        System.Threading.Tasks.Task<Luggage> GetLuggageByIdAsync (string luggageId);

        /// <summary>
        /// Retrieve a luggage item by ID
        /// </summary>
        /// <remarks>
        /// Get detailed information about a specific luggage item. Rate Limiting applies to this endpoint.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="luggageId"></param>
        /// <returns>Task of ApiResponse (Luggage)</returns>
        System.Threading.Tasks.Task<ApiResponse<Luggage>> GetLuggageByIdAsyncWithHttpInfo (string luggageId);
        /// <summary>
        /// List all luggage items
        /// </summary>
        /// <remarks>
        /// Retrieve a list of all luggage items in the system. Rate Limiting applies to this endpoint.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;Luggage&gt;</returns>
        System.Threading.Tasks.Task<List<Luggage>> ListLuggageAsync ();

        /// <summary>
        /// List all luggage items
        /// </summary>
        /// <remarks>
        /// Retrieve a list of all luggage items in the system. Rate Limiting applies to this endpoint.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;Luggage&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<Luggage>>> ListLuggageAsyncWithHttpInfo ();
        /// <summary>
        /// Server heartbeat operation
        /// </summary>
        /// <remarks>
        /// This operation shows how to override the global security defined above, as we want to open it up for all users. Rate Limiting is not applied here.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task PingGetAsync ();

        /// <summary>
        /// Server heartbeat operation
        /// </summary>
        /// <remarks>
        /// This operation shows how to override the global security defined above, as we want to open it up for all users. Rate Limiting is not applied here.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> PingGetAsyncWithHttpInfo ();
        /// <summary>
        /// Update a luggage item
        /// </summary>
        /// <remarks>
        /// Update details of an existing luggage item. Rate Limiting applies to this endpoint.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="luggageId"></param>
        /// <returns>Task of Luggage</returns>
        System.Threading.Tasks.Task<Luggage> UpdateLuggageAsync (LuggageUpdate body, string luggageId);

        /// <summary>
        /// Update a luggage item
        /// </summary>
        /// <remarks>
        /// Update details of an existing luggage item. Rate Limiting applies to this endpoint.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="luggageId"></param>
        /// <returns>Task of ApiResponse (Luggage)</returns>
        System.Threading.Tasks.Task<ApiResponse<Luggage>> UpdateLuggageAsyncWithHttpInfo (LuggageUpdate body, string luggageId);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class DefaultApi : IDefaultApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DefaultApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class
        /// </summary>
        /// <returns></returns>
        public DefaultApi()
        {
            this.Configuration = IO.Swagger.Client.Configuration.Default;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DefaultApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.Options.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Create a new luggage item Create a new luggage record in the system. Rate Limiting applies to this endpoint.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Luggage</returns>
        public Luggage CreateLuggage (LuggageCreate body)
        {
             ApiResponse<Luggage> localVarResponse = CreateLuggageWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create a new luggage item Create a new luggage record in the system. Rate Limiting applies to this endpoint.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>ApiResponse of Luggage</returns>
        public ApiResponse< Luggage > CreateLuggageWithHttpInfo (LuggageCreate body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling DefaultApi->CreateLuggage");

            var localVarPath = "/luggage";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (password) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateLuggage", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Luggage>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Luggage) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Luggage)));
        }

        /// <summary>
        /// Create a new luggage item Create a new luggage record in the system. Rate Limiting applies to this endpoint.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of Luggage</returns>
        public async System.Threading.Tasks.Task<Luggage> CreateLuggageAsync (LuggageCreate body)
        {
             ApiResponse<Luggage> localVarResponse = await CreateLuggageAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create a new luggage item Create a new luggage record in the system. Rate Limiting applies to this endpoint.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (Luggage)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Luggage>> CreateLuggageAsyncWithHttpInfo (LuggageCreate body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling DefaultApi->CreateLuggage");

            var localVarPath = "/luggage";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (password) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateLuggage", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Luggage>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Luggage) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Luggage)));
        }

        /// <summary>
        /// Delete a luggage item Remove a luggage item from the system. Rate Limiting applies to this endpoint.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="luggageId"></param>
        /// <returns></returns>
        public void DeleteLuggage (string luggageId)
        {
             DeleteLuggageWithHttpInfo(luggageId);
        }

        /// <summary>
        /// Delete a luggage item Remove a luggage item from the system. Rate Limiting applies to this endpoint.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="luggageId"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> DeleteLuggageWithHttpInfo (string luggageId)
        {
            // verify the required parameter 'luggageId' is set
            if (luggageId == null)
                throw new ApiException(400, "Missing required parameter 'luggageId' when calling DefaultApi->DeleteLuggage");

            var localVarPath = "/luggage/{luggageId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (luggageId != null) localVarPathParams.Add("luggageId", this.Configuration.ApiClient.ParameterToString(luggageId)); // path parameter
            // authentication (password) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Delete, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteLuggage", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Delete a luggage item Remove a luggage item from the system. Rate Limiting applies to this endpoint.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="luggageId"></param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteLuggageAsync (string luggageId)
        {
             await DeleteLuggageAsyncWithHttpInfo(luggageId);

        }

        /// <summary>
        /// Delete a luggage item Remove a luggage item from the system. Rate Limiting applies to this endpoint.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="luggageId"></param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> DeleteLuggageAsyncWithHttpInfo (string luggageId)
        {
            // verify the required parameter 'luggageId' is set
            if (luggageId == null)
                throw new ApiException(400, "Missing required parameter 'luggageId' when calling DefaultApi->DeleteLuggage");

            var localVarPath = "/luggage/{luggageId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (luggageId != null) localVarPathParams.Add("luggageId", this.Configuration.ApiClient.ParameterToString(luggageId)); // path parameter
            // authentication (password) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Delete, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteLuggage", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Server example operation This is an example operation to show how security is applied to the call. Rate Limiting is enforced to protect the API.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns></returns>
        public void ExampleGet ()
        {
             ExampleGetWithHttpInfo();
        }

        /// <summary>
        /// Server example operation This is an example operation to show how security is applied to the call. Rate Limiting is enforced to protect the API.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> ExampleGetWithHttpInfo ()
        {

            var localVarPath = "/example";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // authentication (password) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ExampleGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Server example operation This is an example operation to show how security is applied to the call. Rate Limiting is enforced to protect the API.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ExampleGetAsync ()
        {
             await ExampleGetAsyncWithHttpInfo();

        }

        /// <summary>
        /// Server example operation This is an example operation to show how security is applied to the call. Rate Limiting is enforced to protect the API.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> ExampleGetAsyncWithHttpInfo ()
        {

            var localVarPath = "/example";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // authentication (password) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ExampleGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Retrieve a luggage item by ID Get detailed information about a specific luggage item. Rate Limiting applies to this endpoint.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="luggageId"></param>
        /// <returns>Luggage</returns>
        public Luggage GetLuggageById (string luggageId)
        {
             ApiResponse<Luggage> localVarResponse = GetLuggageByIdWithHttpInfo(luggageId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve a luggage item by ID Get detailed information about a specific luggage item. Rate Limiting applies to this endpoint.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="luggageId"></param>
        /// <returns>ApiResponse of Luggage</returns>
        public ApiResponse< Luggage > GetLuggageByIdWithHttpInfo (string luggageId)
        {
            // verify the required parameter 'luggageId' is set
            if (luggageId == null)
                throw new ApiException(400, "Missing required parameter 'luggageId' when calling DefaultApi->GetLuggageById");

            var localVarPath = "/luggage/{luggageId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (luggageId != null) localVarPathParams.Add("luggageId", this.Configuration.ApiClient.ParameterToString(luggageId)); // path parameter
            // authentication (password) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetLuggageById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Luggage>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Luggage) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Luggage)));
        }

        /// <summary>
        /// Retrieve a luggage item by ID Get detailed information about a specific luggage item. Rate Limiting applies to this endpoint.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="luggageId"></param>
        /// <returns>Task of Luggage</returns>
        public async System.Threading.Tasks.Task<Luggage> GetLuggageByIdAsync (string luggageId)
        {
             ApiResponse<Luggage> localVarResponse = await GetLuggageByIdAsyncWithHttpInfo(luggageId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieve a luggage item by ID Get detailed information about a specific luggage item. Rate Limiting applies to this endpoint.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="luggageId"></param>
        /// <returns>Task of ApiResponse (Luggage)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Luggage>> GetLuggageByIdAsyncWithHttpInfo (string luggageId)
        {
            // verify the required parameter 'luggageId' is set
            if (luggageId == null)
                throw new ApiException(400, "Missing required parameter 'luggageId' when calling DefaultApi->GetLuggageById");

            var localVarPath = "/luggage/{luggageId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (luggageId != null) localVarPathParams.Add("luggageId", this.Configuration.ApiClient.ParameterToString(luggageId)); // path parameter
            // authentication (password) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetLuggageById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Luggage>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Luggage) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Luggage)));
        }

        /// <summary>
        /// List all luggage items Retrieve a list of all luggage items in the system. Rate Limiting applies to this endpoint.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;Luggage&gt;</returns>
        public List<Luggage> ListLuggage ()
        {
             ApiResponse<List<Luggage>> localVarResponse = ListLuggageWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// List all luggage items Retrieve a list of all luggage items in the system. Rate Limiting applies to this endpoint.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;Luggage&gt;</returns>
        public ApiResponse< List<Luggage> > ListLuggageWithHttpInfo ()
        {

            var localVarPath = "/luggage";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // authentication (password) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ListLuggage", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Luggage>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<Luggage>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Luggage>)));
        }

        /// <summary>
        /// List all luggage items Retrieve a list of all luggage items in the system. Rate Limiting applies to this endpoint.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;Luggage&gt;</returns>
        public async System.Threading.Tasks.Task<List<Luggage>> ListLuggageAsync ()
        {
             ApiResponse<List<Luggage>> localVarResponse = await ListLuggageAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// List all luggage items Retrieve a list of all luggage items in the system. Rate Limiting applies to this endpoint.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;Luggage&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<Luggage>>> ListLuggageAsyncWithHttpInfo ()
        {

            var localVarPath = "/luggage";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // authentication (password) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ListLuggage", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Luggage>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<Luggage>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Luggage>)));
        }

        /// <summary>
        /// Server heartbeat operation This operation shows how to override the global security defined above, as we want to open it up for all users. Rate Limiting is not applied here.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns></returns>
        public void PingGet ()
        {
             PingGetWithHttpInfo();
        }

        /// <summary>
        /// Server heartbeat operation This operation shows how to override the global security defined above, as we want to open it up for all users. Rate Limiting is not applied here.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> PingGetWithHttpInfo ()
        {

            var localVarPath = "/ping";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PingGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Server heartbeat operation This operation shows how to override the global security defined above, as we want to open it up for all users. Rate Limiting is not applied here.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task PingGetAsync ()
        {
             await PingGetAsyncWithHttpInfo();

        }

        /// <summary>
        /// Server heartbeat operation This operation shows how to override the global security defined above, as we want to open it up for all users. Rate Limiting is not applied here.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> PingGetAsyncWithHttpInfo ()
        {

            var localVarPath = "/ping";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PingGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Update a luggage item Update details of an existing luggage item. Rate Limiting applies to this endpoint.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="luggageId"></param>
        /// <returns>Luggage</returns>
        public Luggage UpdateLuggage (LuggageUpdate body, string luggageId)
        {
             ApiResponse<Luggage> localVarResponse = UpdateLuggageWithHttpInfo(body, luggageId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Update a luggage item Update details of an existing luggage item. Rate Limiting applies to this endpoint.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="luggageId"></param>
        /// <returns>ApiResponse of Luggage</returns>
        public ApiResponse< Luggage > UpdateLuggageWithHttpInfo (LuggageUpdate body, string luggageId)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling DefaultApi->UpdateLuggage");
            // verify the required parameter 'luggageId' is set
            if (luggageId == null)
                throw new ApiException(400, "Missing required parameter 'luggageId' when calling DefaultApi->UpdateLuggage");

            var localVarPath = "/luggage/{luggageId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (luggageId != null) localVarPathParams.Add("luggageId", this.Configuration.ApiClient.ParameterToString(luggageId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (password) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Put, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateLuggage", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Luggage>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Luggage) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Luggage)));
        }

        /// <summary>
        /// Update a luggage item Update details of an existing luggage item. Rate Limiting applies to this endpoint.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="luggageId"></param>
        /// <returns>Task of Luggage</returns>
        public async System.Threading.Tasks.Task<Luggage> UpdateLuggageAsync (LuggageUpdate body, string luggageId)
        {
             ApiResponse<Luggage> localVarResponse = await UpdateLuggageAsyncWithHttpInfo(body, luggageId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Update a luggage item Update details of an existing luggage item. Rate Limiting applies to this endpoint.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="luggageId"></param>
        /// <returns>Task of ApiResponse (Luggage)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Luggage>> UpdateLuggageAsyncWithHttpInfo (LuggageUpdate body, string luggageId)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling DefaultApi->UpdateLuggage");
            // verify the required parameter 'luggageId' is set
            if (luggageId == null)
                throw new ApiException(400, "Missing required parameter 'luggageId' when calling DefaultApi->UpdateLuggage");

            var localVarPath = "/luggage/{luggageId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (luggageId != null) localVarPathParams.Add("luggageId", this.Configuration.ApiClient.ParameterToString(luggageId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (password) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Put, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateLuggage", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Luggage>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Luggage) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Luggage)));
        }

    }
}
